[package]
name = "backend_gstreamer"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backend_common = { path = "../backend_common" }
